# docker-compose.yml
version: '3.4'

volumes:
  keycloak_data:
    driver: local
  webapp:
    driver: local
  webapp_data:
    driver: local


services:
  flask-db:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: 'app'
        POSTGRES_USER: 'APPUSER'
        POSTGRES_PASSWORD: 'password'
    ports:
        - 9999:5432
    volumes:
        - webapp_data:/var/lib/postgresql/data

  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      POSTGRES_URL: flask-db:9999
      POSTGRES_USER: 'APPUSER'
      POSTGRES_PW: 'password'
      POSTGRES_DB: 'app'
    volumes:
      - "./webapp:/app"
    depends_on:
      - flask-db

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask

  keycloak-db:
    image: postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - 8888:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_IMPORT: /etc/settings/realm.json
    volumes:
      - ./keycloak:/etc/settings
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
